### ISSUE TITLE
Wiki aktivieren

### ISSUE THREAD

**Issue by zuphilip** [Informationspraxis/artikel-vorlage#14]
Können wir hier auch das Wiki aktivieren?

Da könnte man insbesondere einfach Punkt bei der praktischen Arbeit festhalten oder gar eine Art Checkliste anfangen.

Beispielsweise wollte ich mir gerade notieren, dass Titel und Untertitel im PDF mit Doppelpunkt getrennt werden sollen.

**Comment by felixlohmeier** [comment]
Klar, ich habe Dich zum Admin (via Einladung zum Team "Core") gemacht und das Wiki aktiviert.

**Comment by zuphilip** [comment]
Vielen Dank!
